pipeline {
	agent any
	tools {
		maven "maven"
	}
	stages {
		stage ('Check ENV') {
			steps {
				sh "mvn -v"
				sh "java -version"
			}
		}
		stage ('Test project') {
			steps {
				sh "cd spring/spring-project-backend && mvn test"
			}
		}
		stage ('Build project') {
			steps {
				sh "cd spring/spring-project-backend && mvn package"
			}
		}
	}
}