pipeline {
	agent any
	stages {
		stage ('Check ENV') {
			steps {
				sh "mvn -v"
				sh "java -version"
			}
		}
		
		stage ('mvn clean') {
            steps{
                sh "cd spring/spring-project-backend && mvn clean"
            }
		}
		stage ('Test project') {
			steps {
				sh "cd spring/spring-project-backend && mvn test"
			}
		}
		stage ('Build project') {
			steps {
			    sh "/usr/local/tomcat/bin/shutdown.sh"
				sh "cd spring/spring-project-backend && mvn package"
			    sh "/usr/local/tomcat/bin/deploy.sh"
			}
		}
	}
	post{
	    always{
			sh "/usr/local/tomcat/bin/startup.sh"
	    }
	}
}